include $(APPDIR)/Make.defs

# PWM Example.

MAINSRC = motor_pwm.c

# PWM built-in application info

PROGNAME = motor_pwm
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_MOTOR_PWM)

include $(APPDIR)/Application.mk
