include $(APPDIR)/Make.defs

# PWM Example.

MAINSRC = dbw_wheel.c

# PWM built-in application info

PROGNAME = dbw_wheel
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_DBW_WHEEL)

include $(APPDIR)/Application.mk
