include $(APPDIR)/Make.defs

# PWM Example.

MAINSRC = dbw_steer.c

# PWM built-in application info

PROGNAME = dbw_steer
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_DBW_STEER)

include $(APPDIR)/Application.mk
