include $(APPDIR)/Make.defs

# PWM Example.

MAINSRC = plactool.c

# PWM built-in application info

PROGNAME = plcatool
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_PLCATOOL)

include $(APPDIR)/Application.mk
