include $(APPDIR)/Make.defs

# PWM Example.

MAINSRC = mdio_test.c

# PWM built-in application info

PROGNAME = mdio_test
PRIORITY = SCHED_PRIORITY_DEFAULT
STACKSIZE = $(CONFIG_DEFAULT_TASK_STACKSIZE)
MODULE = $(CONFIG_MDIO_TEST)

include $(APPDIR)/Application.mk
